### ISSUE TITLE
Light Bulbs i boat bay need changing 

### ISSUE THREAD

**Issue by JackLA** [CityRC/Boathouse#1]
It's dark

**Comment by scottodonoghue** [comment]
The broken ones at the front have been replaced.
I'll have a look around the boat bay to see if anymore need replacing.

**Comment by 13enedict** [comment]
I have four GU10 lights that you can have, for what it's worth

**Comment by scottodonoghue** [comment]
Thanks Benedict, that will be useful as there are a fair few lights upstairs that don't work.

**Comment by scottodonoghue** [comment]
The boat bay lights should all be working now. Let me know if there are any more that don't work.
