### ISSUE TITLE
Sculling racks

### ISSUE THREAD

**Issue by JackLA** [CityRC/Boathouse#10]
Work with Equipment officer: We need to label each set of blades properly with a sign behind each rack that is clearly viewable. We also need some end plates on the racks to stop the blades falling off. 

From bottom to top we have: 

Women's double and single blades (put into sets of 2 if possible)
Women's Quad blades
Men's double and sculls blades (put into two sets)
Men's quad blades

**Comment by scottodonoghue** [comment]
In the committee meeting it was noted that the racks have partly come loose from the fittings into the wall and these need to be re-done.
