### ISSUE TITLE
Review bin capacity.

### ISSUE THREAD

**Issue by scottodonoghue** [CityRC/Boathouse#16]
We need to check that we enough capacity to meet our current needs.
Note that membership numbers have risen over the past year and our current membership is arguably more active both in terms of rowing and in the socials.
All in all, we are creating more rubbish.

I plan to have a look through at the bins and whether we may need another trade bin.

**Comment by JackLA** [comment]
Nice one mate, send an email to Claire as she may have rates for all of
this stuff. I know CUBC used to have a trade bin at the back of their
boathouse I used to chuck rubbish in to too.
