### ISSUE TITLE
Ladies shower

### ISSUE THREAD

**Issue by ghost** [CityRC/Boathouse#2]
Shower doesn't really work unless you have it cold - not sure if it needs a new shower head or a new shower!  
Any chance of a shower curtain as well to stop water going over the floor!

**Comment by ghost** [comment]
Oh yes, it also needs a light bulb - showering in the dark or with the door open are not ideal :o)

**Comment by scottodonoghue** [comment]
All the lights should be working now.

I am planning to get a new shower head over the weekend to see if that fixes the problem.

**Comment by scottodonoghue** [comment]
I have replaced the shower head with a new one that works better. Still need to get a shower curtain and rail.

**Comment by scottodonoghue** [comment]
Shower curtain installed.
