### ISSUE TITLE
Leaking in the bar

### ISSUE THREAD

**Issue by NSinclair94** [CityRC/Boathouse#25]
Benedict, this thread is baron. I have therefore taken it upon myself to populate it.

Issue number 1.
There is water leaking all over the floor in the bar

**Comment by 13enedict** [comment]
Would you be a dear and empty the bucket by the sink? Trying to get a plumber

**Comment by NSinclair94** [comment]
Why don't you try your Italian friend again?
There is a bucket there but there is water spiking out from somewhere else

**Comment by 13enedict** [comment]
Yeah, hoping to get the Italian plumber in on Saturday. I'll take a closer
look at the leaks.

**Comment by 13enedict** [comment]
Fixed
