### ISSUE TITLE
Tailwind footplate at 6 seat has lots of problems

### ISSUE THREAD

**Issue by JohnLeighton** [CityRC/Boathouse#30]
Quite a few issues at 6 seat of tailwind. 

Middle corargated grip bit has a chunk missing, so footplate can pull out the grip. Also missing a screw when we had to turn the grip around so taller people can row.  

Bow side grip is very loose. 

Footplate is cracked.

**Comment by 13enedict** [comment]
Hi, you need to open these under https://github.com/CityRC/Equipment this is a different repository
